### PR TITLE
Make the armnn-mobilenet-quant example build with just the installed version of ArmNN (using only the frontend API)

### PR DESCRIPTION
**Pull request by MatteoArm**
This was in response to a request in  ArmNN (https://github.com/ARM-software/armnn/issues/292):

 * Removed the non-public headers usage
 * Added the necessary code/files for the tests to build without any
   ArmNN sources not part of the frontend API
 * Updated the Makefile

Signed-off-by: Matteo Martincigh <matteo.martincigh@arm.com>

### CODE REVIEW

**Comment by ggardet** [comment]
It needs to be rebased, apparently.

**Comment by ggardet** [comment]
@MatteoArm I think you deleted the branch without a merge.

**Comment by MatteoArm** [comment]
@ggardet I wasn't happy with merging master into the branch to fix the merge, so I've created a new PR where I just rebased the changes on top of master directly, as you suggested at the time.
The new PR is https://github.com/ARM-software/ML-examples/pull/35

**Comment by ggardet** [comment]
> @ggardet I wasn't happy with merging master into the branch to fix the merge, so I've created a new PR where I just rebased the changes on top of master directly, as you suggested at the time.
> The new PR is #35

A `git rebase` + `git push -f` would have done it ;)

**Pull request closed without merging**
